import = [
  "~/.config/alacritty/themes/themes/nightfox.toml"
]
[env]
TERM = "xterm-256color"

[window]
padding.x = 6
padding.y = 6
decorations = "Buttonless"
startup_mode = "Fullscreen"

opacity = 0.7
blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style = "SemiBold"
size = 16


